# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [82]:
# Create a 1-dimensional NumPy array using np.array()

one_d = np.array([1,2,4])
# Create a 2-dimensional NumPy array using np.array()

Two_d = np.ones((2,2))
# Create a 3-dimensional Numpy array using np.array()

Third_d = np.random.randint(10,size=(3,3,2))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [87]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_d.shape,one_d.ndim,one_d.dtype,type(one_d),one_d.size

((3,), 1, dtype('int64'), numpy.ndarray, 3)

In [88]:
# Attributes of 2-dimensional array
Two_d.shape,Two_d.ndim,Two_d.dtype,type(Two_d),Two_d.size

((2, 2), 2, dtype('float64'), numpy.ndarray, 4)

In [89]:
# Attributes of 3-dimensional array
Third_d.shape,Third_d.ndim,Third_d.dtype,type(Third_d),Third_d.size

((3, 3, 2), 3, dtype('int64'), numpy.ndarray, 18)

In [86]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

df = pd.DataFrame(one_d)
df

0
0  1
1  2
2  4

In [18]:
# Create an array of shape (10, 2) with only ones

np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# Create an array of shape (7, 2, 3) of only zeros

np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
# Create an array within a range of 0 and 100 with step 3

np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
# Create a random array with numbers between 0 and 10 of size (7, 2)

np.random.randint(0,10,size=(7,2))

array([[8, 7],
       [1, 9],
       [5, 7],
       [0, 5],
       [3, 1],
       [9, 6],
       [7, 0]])

In [22]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

np.random.rand(3,5)

array([[0.369828  , 0.04184993, 0.59799829, 0.97337474, 0.51515496],
       [0.2083815 , 0.61542137, 0.23057224, 0.54795424, 0.01739751],
       [0.39962218, 0.37553751, 0.07266299, 0.0504497 , 0.43201703]])

In [24]:
# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)

np.random.randint(0,10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?
- np.random.seed() is a pseduo function it runs as same when the cell is tries to run for multiple times and the values are not changed.

In [25]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

random_array = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(random_array)

array([1, 2, 3, 4, 5, 7, 9])

In [27]:
random_array

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [26]:
# Find the 0'th index of the latest array you created

random_array[0]

array([9, 1, 3, 7, 4, 9, 3])

In [28]:
# Get the first 2 rows of latest array you created

random_array[ :2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [31]:
# Get the first 2 values of the first 2 rows of the latest array

random_array[:2 ,:2]

array([[9, 1],
       [5, 3]])

In [33]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

rand_arr = np.random.randint(0,10,size=(3,5))
rand_ones = np.ones((3,5))
rand_ones,rand_arr

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]]))

In [35]:
# Add the two arrays together

rand_arr+rand_ones

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [37]:
# Create another array of ones of shape (5, 3)

ones = np.ones((5,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
# Try add the array of ones and the other most recent array together

ones+rand_ones

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?
- The shape of the array is not same so it cannot  be added
- To fix this the shape must be 1 or equal 

In [40]:
# Create another array of ones of shape (3, 5)

ones_3 = np.ones((3,5))
ones_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
# Subtract the new array of ones from the other most recent array

ones_3 - rand_ones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
# Multiply the ones array with the latest array

rand_ones *ones_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
# Take the latest array to the power of 2 using '**'

ones_3 ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
# Do the same thing with np.square()

np.square(ones_3)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
# Find the mean of the latest array using np.mean()

np.mean(ones_3)

1.0

In [51]:
# Find the maximum of the latest array using np.max()

np.max(ones_3)

1.0

In [52]:
# Find the minimum of the latest array using np.min()

np.min(ones_3)

1.0

In [53]:
# Find the standard deviation of the latest array

np.std(ones_3)

0.0

In [54]:
# Find the variance of the latest array

np.var(ones_3)

0.0

In [57]:
# Reshape the latest array to (3, 5, 1)

ones_3.reshape((3,5,1))

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [58]:
# Transpose the latest array

ones_3.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

What does the transpose do?
- In transpose the rows is interchanged into column and column in interchanged into row. 

In [62]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

a = np.random.randint(0,10,size=(3,3))
b = np.random.randint(0,10,size=(3,2))
a,b

(array([[9, 6, 9],
        [8, 6, 8],
        [7, 1, 0]]),
 array([[6, 6],
        [7, 4],
        [2, 7]]))

In [64]:
# Perform a dot product on the two newest arrays you created

np.dot(a,b)

array([[114, 141],
       [106, 128],
       [ 49,  46]])

In [65]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

c = np.random.randint(0,10,size=(4,3))
d = np.random.randint(0,10,size=(4,3))

In [66]:
# Perform a dot product on the two newest arrays you created
np.dot(c,d)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?
- The column size of the c does'nt match with the row size of d.
- By trandposing the d the error could be fixed.

In [67]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

np.dot(c,d.T)

array([[ 63,  30,  23,  36],
       [ 58,  18,  34,  36],
       [ 54,  27,  70,  66],
       [124,  60,  90, 102]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [69]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

e = np.random.randint(0,10,size = (3,3))
f = np.random.randint(0,10 ,size=(3,3))

In [70]:
# Compare the two arrays with '>'
e >f

array([[False, False, False],
       [ True,  True, False],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

- The > checks the each element in the array e and f, then the bool value is printed.

In [71]:
# Compare the two arrays with '>='
e>=f

array([[False, False, False],
       [ True,  True, False],
       [False,  True,  True]])

In [72]:
# Find which elements of the first array are greater than 7

e >7

array([[False, False, False],
       [ True,  True, False],
       [False, False,  True]])

In [73]:
# Which parts of each array are equal? (try using '==')

e==f

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

In [74]:
# Sort one of the arrays you just created in ascending order

np.sort(e)

array([[1, 2, 5],
       [4, 8, 9],
       [3, 5, 9]])

In [75]:
# Sort the indexes of one of the arrays you just created
np.argsort(e)

array([[2, 0, 1],
       [2, 1, 0],
       [1, 0, 2]])

In [76]:
# Find the index with the maximum value in one of the arrays you've created

np.argmax(e)

3

In [77]:
# Find the index with the minimum value in one of the arrays you've created

np.argmin(e)

2

In [78]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

np.argmax(e,axis=1)

array([1, 0, 2])

In [79]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

np.argmax(e,axis=0)

array([1, 1, 2])

In [91]:
# Create an array of normally distributed random numbers

np.random.randn(3,3)


array([[-1.45851692,  0.4777541 , -0.25902864],
       [-0.57470921, -0.42149822,  0.33982096],
       [-0.00738015,  0.76729684, -1.14979258]])

In [81]:
# Create an array with 10 evenly spaced numbers between 1 and 100

np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [92]:
# or 
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.